// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZq9GmRc8-B6wA7ER2etiVIUfsPlNvI_0',
    appId: '1:993358352828:android:9dad0af2c665a9b69b5bb9',
    messagingSenderId: '993358352828',
    projectId: 'mapsy-40e92',
    storageBucket: 'mapsy-40e92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3zcZ7KiHbxHquaAD07zQ94-TY_ypV_IE',
    appId: '1:993358352828:ios:c0dabea82eebf2789b5bb9',
    messagingSenderId: '993358352828',
    projectId: 'mapsy-40e92',
    storageBucket: 'mapsy-40e92.firebasestorage.app',
    iosBundleId: 'com.elipair.mapsy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3zcZ7KiHbxHquaAD07zQ94-TY_ypV_IE',
    appId: '1:993358352828:ios:37ff835d682dc7199b5bb9',
    messagingSenderId: '993358352828',
    projectId: 'mapsy-40e92',
    storageBucket: 'mapsy-40e92.firebasestorage.app',
    iosClientId:
        '993358352828-esehccg0b6bb1lo1gof18sqvr1ndo1rr.apps.googleusercontent.com',
    iosBundleId: 'com.example.mapsy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG0987HWPxQNdjz6nBUNYb8EanAbdGIjg',
    appId: '1:993358352828:web:0c08f155114875399b5bb9',
    messagingSenderId: '993358352828',
    projectId: 'mapsy-40e92',
    authDomain: 'mapsy-40e92.firebaseapp.com',
    storageBucket: 'mapsy-40e92.firebasestorage.app',
    measurementId: 'G-NLKRC1JQGB',
  );
}
